services:
  devos:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    # Mapping parent of .devcontainer folder into the container
    # This ensures that all the code is available for version control
    volumes:
      - ..:/rustpg

    # Adding sleep command so container remains running
    command: sleep infinity
